# Generated by Django 3.2 on 2023-09-19 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230918_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя может\n                содержать только буквы,\n                цифры и символы @/./+/-/_', regex='^[\\w.@+-]+$')]),
        ),
    ]
